// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// Controllers is an autogenerated mock type for the Controllers type
type Controllers struct {
	mock.Mock
}

// CreateCard provides a mock function with given fields: c
func (_m *Controllers) CreateCard(c *gin.Context) {
	_m.Called(c)
}

// DeleteCard provides a mock function with given fields: c
func (_m *Controllers) DeleteCard(c *gin.Context) {
	_m.Called(c)
}

// GetCards provides a mock function with given fields: c
func (_m *Controllers) GetCards(c *gin.Context) {
	_m.Called(c)
}

// GetSpecificCard provides a mock function with given fields: c
func (_m *Controllers) GetSpecificCard(c *gin.Context) {
	_m.Called(c)
}

// Ping provides a mock function with given fields: c
func (_m *Controllers) Ping(c *gin.Context) {
	_m.Called(c)
}

// UpdateCard provides a mock function with given fields: c
func (_m *Controllers) UpdateCard(c *gin.Context) {
	_m.Called(c)
}

// NewControllers creates a new instance of Controllers. It also registers a cleanup function to assert the mocks expectations.
func NewControllers(t testing.TB) *Controllers {
	mock := &Controllers{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
